### ISSUE TITLE
Fix discovery tests

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#225] opened 2018-02-01 13:50 UTC
fix network/simulations/discovery_test.go and rework it using p2p/testing/simulations

**Comment by nonsense** [comment] 2018-02-05 10:24
@gbalint Could you explain in detail what you mean with `fix network/simulations/discovery_test.go`? Discovery tests are working fine with the `sim` and `sock` adapters, but are not working with the `exec` adapter. `exec` is failing because of:

```
// NewAddrFromNodeID constucts a BzzAddr from a discover.NodeID
// the overlay address is derived as the hash of the nodeID
func NewAddrFromNodeID(id discover.NodeID) *BzzAddr {
    return &BzzAddr{
        OAddr: ToOverlayAddr(id.Bytes()),
        UAddr: []byte(discover.NewNode(id, net.IP{127, 0, 0, 1}, 30303, 30303).String()),
    }
}
```

which is assigning port 30303 to all nodes, and not the port that the kernel randomly assigned to the `exec` nodes.

Could you please confirm that this is the problem that this issue is about, or is there something else to be fixed?

**Comment by zelig** [comment] 2018-02-05 15:17
@nonsense indeed this would be great to fix if  you can
this issue was meant to be about reworking the test to use the same test setup as the stream simulation test using `swarm/stream/testing`  which should move to `swarm/network/testing`
but the issue is not super high priority

**Comment by nonsense** [comment] 2018-02-08 13:14
@zelig @gbalint the PR is merged and tests are passing. I think we can translate the tests to the same test setup as the stream simulation test later, once we get to an overall green build of our main branch - I think this particular re-write of tests is not a high priority right now.

**Comment by zelig** [comment] 2018-02-08 17:38
@nonsense please go ahead with the green build yes

**Closed as completed** 2018-02-17 09:19 UTC
