### ISSUE TITLE
Error handling submitting/cashing cheques

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1635] opened 2019-08-02 08:48 UTC
Currently, we only log an error when we can't submit / cash a cheque. 
Getting an error from the blockchain can mean two things: 

1) sending the transaction to the blockchain failed
2) the transaction was send to the blockchain, but triggered a revert (smart-contract condition)

In the first case, it can be due to some local configuration (i.e. private key not set, no connection with testnet).
In the second case, it is because the cheque was incorrectly formatted or the cheque was already submitted. 

Handling the error should strive towards cashing the cheque if possible. If not possible, the amount of the cheque should be added back to the peer balance.

**Comment by mortelli** [comment] 2019-09-04 19:36
See also #1601.

**Comment by mortelli** [comment] 2019-09-06 15:16
Marking this as `on hold` since we are waiting for:
1. #1725 to be finished first
2. error flow specification and/or diagram to be elaborated

**Comment by holisticode** [comment] 2019-10-01 20:20
Duplicate of https://github.com/ethersphere/swarm/issues/1601

**Closed as completed** 2019-10-01 20:20 UTC
Labels: on hold, priority, incentives
