### ISSUE TITLE
cmd/swarm: Ambiguous defaults in `swarm --help`

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#829] opened 2018-08-01 12:16 UTC
for example:

```
   --bzznetworkid value               Network identifier (integer, default 3=swarm testnet) (default: 0) [$SWARM_NETWORK_ID]
```

**Comment by nolash** [comment] 2019-02-26 16:26
@nonsense Why close it? I have currently (f0233948d2bc343deb17be06c1a0f93c3e004084) for example:

```
   --sync-update-delay value          Duration for sync subscriptions update after no new peers are added (default 15s) (default: 0s) [$SWARM_ENV_SYNC_UPDATE_DELAY]
```

**Comment by nonsense** [comment] 2019-02-26 16:32
@nolash because it is a duplicate of https://github.com/ethersphere/go-ethereum/issues/1143 which has a better description.

**Closed as completed by nonsense** 2019-02-26 16:32 UTC
Labels: bug, good first issue, cli
