### ISSUE TITLE
Improve node identification in logs

### ISSUE THREAD

**Issue by janos** [ethersphere/swarm#1961] opened 2019-11-18 10:38 UTC
Swarm node is currently identified by both network.BzzAddr and enode.ID. BzzAddr contains both Overlay (swarm) address and Underlay (ethereum node v4) addresses. Underlay address corresponds with enode.ID, but Overlay address cannot be derived from Underlay address. Identifying nodes in logs and in simulations require looking up one or another address for relations.

There should be an investigation which changes are needed in the codebase in order to log IDs so that the nodes are more easily identified. 

Note: network.NewBzzAddrFromEnode is not correct and it should be used only in tests, eventually, not even there.

**Comment by acud** [comment] 2019-11-25 10:04
duplicate of https://github.com/ethersphere/swarm/issues/1617

**Closed as completed** 2019-11-25 10:04 UTC
Labels: good first issue
