### ISSUE TITLE
network/stream: TestGetSubscriptionsRPC is flaky with -race (ratio: 22:1000)

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1234] opened 2019-02-19 09:06 UTC
**Problem**

```
--- FAIL: TestGetSubscriptionsRPC (0.37s)
    streamer_test.go:1332: Real subscriptions and expected amount don't match; real: 1, expected: 8
```

**Flaky ratio**
```
     20 FAIL
    980 PASS
```
~~*Note:* because of #1233  I did not get a 1000 runs as originally intended.~~

**How to reproduce**

`time go test -v -race -run TestGetSubscriptionsRPC -count 1000 github.com/ethereum/go-ethereum/swarm/network/stream`

*Note*: The test seems to be stable without `-race`.

**Comment by janos** [comment] 2019-02-19 10:42
I cannot reproduce the failures with code from https://github.com/ethersphere/go-ethereum/pull/1237. But, the changes in that PR should not be relevant for the TestGetSubscriptionsRPC results.

**Comment by frncmx** [comment] 2019-02-19 12:42
@janos hmm....might be?  The failure happened when my computer froze and some browser windows crashed. The test runtime increased sometime the test got completely stuck before failing. ... maybe the failures happened because the extensive memory usage

**Comment by frncmx** [comment] 2019-02-19 12:47
I run the tests on my machine again with the fix. Now the flakiness stopped.

**Comment by janos** [comment] 2019-02-19 12:49
@frncmx cool, thanks.

**Comment by frncmx** [comment] 2019-02-19 13:32
@janos I just assigned this to you so others won't consider picking this up when looking at the board. When your PR gets merged this will be automatically closed and moved to done.

**Comment by janos** [comment] 2019-02-19 13:41
@frncmx thanks.

**Comment by janos** [comment] 2019-02-20 09:49
I still have very rare failures even with fixes from https://github.com/ethereum/go-ethereum/pull/19139. I believe that a timeout for waiting for subscriptions may be too short in this test when the load is high, as failures are present when the test run is a bit longer. I still have no hard proof for that. But I will create a PR with increased timeout when https://github.com/ethereum/go-ethereum/pull/19139 is merged.

**Comment by frncmx** [comment] 2019-02-20 10:09
At first glance, the flakiness might be really a timing issue, as the test uses timers (`syncUpdateDelay`, `waitDuration`) to sync events. That's fragile by it's nature.

The test in not neat. Though I'm not sure how many failures we get on our CI if any, so be careful with rabbit holes vs. impact. :) Good job with the gourtine leak fix. :medal_military:

**Comment by frncmx** [comment] 2019-02-20 10:10
Btw what does extremely rare mean? What is the ratio after the fix?

**Comment by janos** [comment] 2019-02-20 10:19
Thanks @frncmx. :) Yes, timings are fragile, indeed. I have around 1:1000 locally.

There is another issue, a panic, that I found and it is related to synchronizing handleSubscribeMsg (and other rpc mesages) with closing leveldb, I assume. I will create an issue.

**Comment by holisticode** [comment] 2019-03-02 16:48
I think that test actually has a bug. I fixed something in the `longrunning` branch, but as the longrunning tests are not passing yet on the k8s infrastructure, there is no PR for it.

I think that should address the issue

**Comment by frncmx** [comment] 2019-03-05 13:59
@holisticode I guess you mean this line: https://github.com/ethereum/go-ethereum/compare/master...ethersphere:longrunning#diff-7162dde927e91f9905c7f08b266a1c7aL1334
That would be nice if that line would fix it.

@janos this task spent 12 days in Warm columns. :police_car: Shall we remove you as assignee and throw this back to TODO? What's your take? Are you still investigating? :blush:

**Comment by janos** [comment] 2019-03-05 14:56
@frncmx I actually thought that this was fixed by some of the earlier PRs, but I did not close it. At least I could not reproduce it locally and I did not see this test failing on Travis when testing other tests with race detector. Maybe we can close it, as I still cannot reproduce the failure, unless @holisticode have different findings.

**Comment by holisticode** [comment] 2019-03-06 16:45
This issue should have been fixed by https://github.com/ethereum/go-ethereum/pull/19227.

**Comment by holisticode** [comment] 2019-03-06 16:46
@janos you were not able to reproduce it because, due to unfortunate `syncUpdateDelay` and `waitDuration` values in the test, actually no subscriptions were being done - thus `expectedCount` and `realCount` would be `0` - which would make the test pass :)

**Comment by janos** [comment] 2019-03-07 08:13
@holisticode I am sure that I have got errors like:

```
    streamer_test.go:1344: Real subscriptions and expected amount don't match; real: 2, expected: 3
```

Which means that there were some subscriptions, but very likely that the subscriptions were actually at 0 most of the times, which is very unfortunate, waitDuration timing is not the best way to ensure synchronization. I am sure that your PR will fix the problem. Thank you.

**Comment by frncmx** [comment] 2019-03-07 11:23
I run these tests on the current master, 2fa9e99fc19d2804d2409ab5904f4c154e70e6cd.
I forgot to set `-timeout 0` so the test run got killed after 10 minutes but I've he following results.

The test seems to be stable _without_ the `-race` flag. However, the test continues to fail with `-race` if I remove `t.Skip()`.

- without `-race`: 565 PASS, 0 FAILURE
- with  `-race`: 498 PASS, 15 FAILURE


Output samples for failures:

```
=== RUN   TestGetSubscriptionsRPC
ESC[31mERRORESC[0m[03-07|12:05:42.806|p2p/protocols/protocol.go:235] peer.handleIncoming                      ESC[31merrESC[0m="Message handler error: (msg code 7): subscribe to peer 77ba145a4623b9c83e0a14a375ba49c68719f2abe162ffca66de7ef2e31a75f8: client params SYNC|d|l already set"
ESC[31mERRORESC[0m[03-07|12:05:42.810|p2p/protocols/protocol.go:235] peer.handleIncoming                      ESC[31merrESC[0m="Message handler error: (msg code 8): write tcp 127.0.0.1:49126->127.0.0.1:44469: write: connection reset by peer"
--- FAIL: TestGetSubscriptionsRPC (1.12s)
    streamer_test.go:1343: Real subscriptions and expected amount don't match; real: 152, expected: 150
```

```
=== RUN   TestGetSubscriptionsRPC
ESC[31mERRORESC[0m[03-07|12:06:00.185|p2p/protocols/protocol.go:235] peer.handleIncoming                      ESC[31merrESC[0m="Message handler error: (msg code 7): subscribe to peer 77ba145a4623b9c83e0a14a375ba49c68719f2abe162ffca66de7ef2e31a75f8: client params SYNC|g|l already set"
--- FAIL: TestGetSubscriptionsRPC (1.16s)
    streamer_test.go:1343: Real subscriptions and expected amount don't match; real: 152, expected: 150
```

```
=== RUN   TestGetSubscriptionsRPC
[31mERROR[0m[03-07|12:09:21.500|p2p/protocols/protocol.go:235]        peer.handleIncoming                      [31merr[0m="Message handler error: (msg code 9): client not found for stream \"SYNC|5|l\""
[31mERROR[0m[03-07|12:09:21.504|p2p/protocols/protocol.go:235]        peer.handleIncoming                      [31merr[0m="Message handler error: (msg code 9): client not found for stream \"SYNC|0|l\""
--- FAIL: TestGetSubscriptionsRPC (1.28s)
    streamer_test.go:1343: Real subscriptions and expected amount don't match; real: 118, expected: 151
```

@holisticode any ides what might cause that?

**Comment by frncmx** [comment] 2019-03-07 11:47
The same with a 1000 runs:

- without `-race`: PASS 1000 FAIL 0
- with `-race`: PASS 980 FAIL 20 

Currently the test is skipped if `-race` is set. I guess the normal CI run now will be stable.
Do we want to invest more in this?

**Comment by janos** [comment] 2019-03-07 11:50
This test was problematic from start, and we invested a lot of time to fix it. It would be shame to skip it. Maybe we can learn more from it?

**Comment by holisticode** [comment] 2019-03-07 16:48
I just ran the same test and it succeeded:
```
>$ go test -v -race -timeout 0 ./swarm/network/stream/ -run GetSubscriptionsRPC -count 1000
```

```
PASS
ok  	github.com/ethereum/go-ethereum/swarm/network/stream	1187.507s
```

This means I can't really do anything myself, as I can not reproduce this

**Comment by frncmx** [comment] 2019-03-07 19:50
@holisticode Very interesting. I was thinking about the operating system, but I realized you also run Linux. I think I'll run the same command on Travis. If that also succeeds I'll close this ticket as it may happen only on my computer.

What is your kernel and go version just from curiosity?

I have:
```
$ go version
go version go1.12 linux/amd64
$ uname -r
4.18.16-arch1-1-ARCH
```

**Comment by holisticode** [comment] 2019-03-07 19:52
```
$ go version
go version go1.11.5 linux/amd64
$ uname -r
4.9.159-1-MANJARO
```

**Comment by frncmx** [comment] 2019-03-08 12:46
So the problem is happening on Travis, too.
https://travis-ci.org/frncmx/go-ethereum/builds/503582252

**Comment by holisticode** [comment] 2019-03-08 14:49
Then I guess someone else needs to look at it, as I can't reproduce it here?

**Comment by holisticode** [comment] 2019-03-08 18:20
One thing you could be trying is to set `syncUpdateDelay()` to something like `600 * time.Millisecond` and try that on Travis

**Closed as completed** 2019-09-11 14:56 UTC
Labels: bug, test, stability, flaky test
