### ISSUE TITLE
Implement an MVP on-chain price oracle

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1632] opened 2019-08-02 08:32 UTC
Currently, the go-code houses a file ``oracle.go``. To make the codebase more realistic, we should implement a very simple on-chain price oracle.

**Comment by holisticode** [comment] 2019-08-02 16:01
Keep in mind that we need easy unit testing, and we may not want to have to run blockchains for simple tests. So we will need mocking of the on-chain oracle or something equivalent.

**Comment by holisticode** [comment] 2019-10-01 20:24
Duplicate of https://github.com/ethersphere/swarm/issues/1848

**Closed as completed by holisticode** 2019-10-01 20:24 UTC
Labels: incentives
