### ISSUE TITLE
Validation errors in open cluster logs

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#444] opened 2018-04-26 13:28 UTC
Lot of errors like this

swarm_30403 ERROR[04-26|12:25:15.028678|swarm/storage/types.go:349] invalid content address expected=7f820d95ee79dad139815f1af3b15a9c85a618428e22944c708dd2c041669d2b have=f6bb1dd7cd42b6fce0c9c812cdda9ce15a7f06aa9e8dc082eca895ae3f997c7e

**Comment by janos** [comment] 2018-05-29 15:41
Chunks on addresses in the log line are no longer retrievable from open cluster or local node connected to it.

The same error log message from this issus was noticed for `http://localhost:8500/bzz-raw:/8a67f796ced5661c3201a54bd228d6a384d9b5f9ecd4d4d19879306cdb61fc52/`, which is a 275GB long file with all zero bytes. Requesting this file with `bzz://` is resulting with a different error `Manifest size of 295514341376 bytes exceeds the 5242880 byte limit` since this PR https://github.com/ethersphere/go-ethereum/pull/491 is merged. Previously, validation error is raised for this chunk address.

We should keep this issue if errors are noticed again, but currently, I can not reproduce them.

**Comment by janos** [comment] 2018-06-06 14:53
Small update on this issue.

Inspecting more invalid hashes found on open cluster logs, one common property is that their size is quite big.

```
swarm_30401 ERROR[06-06|06:03:06.531899|swarm/storage/types.go:349] invalid content address expected=fc92b891bf80233c738db9951bad61b068269b7598309280f22e096b922d60c0 have=0055b87aab8eddc642d74dda73bd43742871083f2654f4a82ff0578ce87a6a7f
swarm_30401 ERROR[06-06|06:02:55.102529|swarm/storage/types.go:349] invalid content address expected=a1df39a36fe5d670cea5b238008f4f66c17211a9f5b8912fe6c82fd33cd5281f have=10de9e4ad2b2b03b27599b2c258fe3c16d8721dfa43505ef3ea4c0caed007d34
swarm_30402 ERROR[06-06|12:59:50.08087|swarm/storage/types.go:349] invalid content address expected=2995211720a979ea50e1be585a0d03be3117f66b2da056859d8e10b66920badf have=1727198dd949124f90f9c2d96b4485e26cb47582ac90cd3f068dcfcef23bfa55
swarm_30402 ERROR[06-06|12:59:50.09116|swarm/storage/types.go:349] invalid content address expected=b59f8b8825fae9aa449eb4c9df0e486c22a46144a4cdddef51313d4059f8501a have=0fc550ef609dd3d79ef3de2b8e03cf7f8e70ef218a16d4718ee0f341e266b451
```

```
0055b87aab8eddc642d74dda73bd43742871083f2654f4a82ff0578ce87a6a7f: 4298244122 bytes
10de9e4ad2b2b03b27599b2c258fe3c16d8721dfa43505ef3ea4c0caed007d34: 8594456603 bytes
1727198dd949124f90f9c2d96b4485e26cb47582ac90cd3f068dcfcef23bfa55: 266287972379 bytes
0fc550ef609dd3d79ef3de2b8e03cf7f8e70ef218a16d4718ee0f341e266b451: 266291642395 bytes
```

Download this files on local node fails as some chunks are not retrievable for this files, which is another problem with retrieving chunks, but makes harder to replicate this issue locally.

**Comment by janos** [comment] 2018-06-07 09:40
As an attempt to replicate the issue locally, I identified one chunk that is invalid with:

```
DEBUG [06-07|11:34:11.457621] Validate                                 addr=5cc6c9cf5bd94a298bafba6a1df432b211f2d1674fbc3f15fae2802c6b5b969e len=18   data=000012a93000000000002a00000000000000
ERROR[06-07|11:34:11.457661] invalid content address                  expected=890d20b8db50eda96df39e15c6e19746c03bb0ef8880936e35f1bdeba00a71c7 have=5cc6c9cf5bd94a298bafba6a1df432b211f2d1674fbc3f15fae2802c6b5b969e 
```

The `data` in debug log line is the complete Chunk.SData passed to validator.

**Comment by gbalint** [comment] 2018-06-07 12:13
@janos if the size is coming from the span of the chunk, that is not valid if the chunk is encrypted

**Comment by janos** [comment] 2018-06-07 15:16
Apropos suggestion on today's standup, @zelig, uploading files with all the same bytes ( zero or any other byte) is successful and works as expected.

**Comment by janos** [comment] 2018-06-11 15:16
After more logging has been deployed to test cluster thanks to @nonsense, we got chunk's data that are causing the issue:

```
swarm_30402 DEBUG[06-11|14:36:57.792845|swarm/storage/types.go:351] invalid content address data addr=61ab79895eccc324776d51542f8a5195b27f48ea0d9561992a13da7bc886daa1 data=48000000010000000100000095c8de48ffa1bfcbe0fb55c0bb5ec6eed6382550b34ce748de48a071e609d08e06cc96b52a2d17162fa9de20441eecbe3d58f33c142aa60a9646a8ecfdc9b0f71b204a6cfc30084b3529ee59b942e5d4bebdd0d5b94b6f4f8611447cf5ef7a8cd33e29b6789a9d74a757bfe3266843e448e9b75cfd5c253438d52eaa0fc7d64cc09576b2054baa2dadc234786bd314b02f3342735afd3d919aa0f41bc9a7512343a401
swarm_30402 DEBUG[06-11|14:36:57.811449|swarm/storage/types.go:351] invalid content address data addr=3356aa11d8d9bf506cb418e46d578154c45b24518271e7d28b9b02fc03a77ca1 data=10000000010000000100000077686174657665721b2053c991ea136052e7de145ee246b4d17b11ba162ce1d39dcb64c372c630088247776dd9f39c5e6492afb0b5f997a2fdcc98edf98460a61a2454c71c79691a996358601b18bb33f9b710548f9e171bedda5ee6a4db6ac191d850f631db8064a72700
swarm_30404 DEBUG[06-11|14:37:40.604196|swarm/storage/types.go:351] invalid content address data addr=c1cc8e9a6e5bffc9ffd918963e21f14e560a4cdcc09603c373566e47cee9b7ae data=10000000010000000100000077686174657665721b20c03cc163db49f1e7a5fc12158053ccae50f1f2e58b4cee0bfbc9eedfd0fbdcca21a6073c7a7e1806e247fffe22067e8483c988f34d0a53b2c9207f6d7fdcfaa66439bea8ad52fee2cd2ba62555ce3b0c04e146c306d89086973896420015c3e701
```

There is a strange pattern in data encoding that does not look like it is from the standard chunk SData encoding, with first 8 bytes being the size.

@nolash could you check the data key in error logs in this comment and check if the data encoding looks like something that was or still is related to mru?

**Comment by janos** [comment] 2018-06-14 09:22
The same errors are on open cluster very soon after the data is cleared. Addresses that are reported to have invalid data are still returning headers reporting fairly large files using bzz-raw. 

```
swarm_30403 ERROR[06-13\|16:30:00.783288\|swarm/storage/types.go:349] invalid content address expected=60fc8caef47233012d2cf98270c169c97872cfaff14d3b7eafaea1eec04eda0a have=c08a2f7224a92be8cb725b27b49e02b75a93165fcf4c80561c158d0e39163df0
swarm_30400 ERROR[06-13\|16:32:44.918422\|swarm/storage/types.go:349] invalid content address expected=69935e75d8787248d5413b0943c86e70433e651077a87fbcd6f65f192fa54fe9 have=38a695ad5bcad4da21f7dc85e607be508d75f9886959000d6ff1e5003cb4c76c
swarm_30400 ERROR[06-13\|16:33:55.854356\|swarm/storage/types.go:349] invalid content address expected=ec9b274fceaf63a7c6f5bc906e2e52523ef643748056a201738acbf41426f5a0 have=ba0c9777d0d4b724680af0127691bc63cb1f4c973054f75b912889a672f32809
swarm_30402 ERROR[06-13\|16:40:51.026102\|swarm/storage/types.go:349] invalid content address expected=9ca75bc4e785e3de9477d257a0a6c8877c55cef4f36af56c7be0432e8f8ea968 have=9d48ca683b8a4e9112d9bfb349561163b2b408eed90454a81cad8b5fdb8c26b4
```

**Comment by zelig** [comment] 2018-06-14 09:48
as I said before this should not report anything here. This is not an error or even a warning.

https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/swarm/storage/types.go#L353

this line can be removed

**Comment by janos** [comment] 2018-06-14 09:50
Thanks @zelig, submitting a PR.

**Comment by janos** [comment] 2018-06-15 07:49
This is handled in https://github.com/ethersphere/go-ethereum/pull/715.

**Closed as completed by janos** 2018-06-15 07:49 UTC
Labels: bug
